upgrade libdrm-2.4.75 to libdrm-2.4.109
illumos/gfx-drm pull request #25
Opened 2021-12-30 16:48 UTC by klausz65

And add initial SPARC support for drm module

2021-12-31 20:08 UTC, randyfishel commented
To the best of my knowledge, there is no gfx_private for Sparc, so the LDFLAGS on line 50 would at best cause a load failure (would be a pain to port given gfx_private's intensive use of x86-specific facilities).  And I am unaware of any Sparc frame buffer driver that is still around that uses DRM (could possibly be one in the future, but wouldn't it be better to cross that bridge then?).

2022-01-03 18:05 UTC, gwr commented
There's a lot here.  Let me look at this later.  Thanks.

2022-01-03 23:26 UTC, gwr requested changes
For the most part, this looks good.  Thanks for giving this some attention.
I added a few minor improvements and put them in another PR
https://github.com/illumos/gfx-drm/pull/26
Feel free to incorporate those as you like.

2022-01-03 23:27 UTC, gwr commented on usr/src/Makefile.master
> +TAR=		/usr/bin/gtar
I see, we need to unpack an xz file now.

2022-01-03 23:28 UTC, gwr commented on usr/src/common/libdrm/patches/xf86drm-c.patch
> -+	/* else ... (ret NULL at endif) */
I added both those parts back for you in https://github.com/illumos/gfx-drm/pull/26

2025-02-15 12:52 UTC, closed without merging